[client]
showSidebarNavigation = true

[server]
runOnSave = true

[theme]
# Primary accent for interactive elements
primaryColor = '#1b82ff'

# Background color for the main content area
backgroundColor = '#3d3d3d'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#555555'  # f5bcea

# Color used for almost all text
textColor = '#fafafa'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

